[project]
name = "videos-yolo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ultralytics",
    "opencv-python",
    "typer>=0.16.0",
    "lap>=0.5.12",
]
